/**
 * Citation fixtures for cite.test.ts.
 *
 * Copied from the retired src/sources.ts (2026-09-30) so the formatter tests
 * keep running offline. The live values are the `cite` column of
 * public.references_resources; these don't have to track them.
 */

import type { SourceCitation } from './cite'

export type CiteFixture = { id: string; href: string; cite: SourceCitation }

export const CITE_FIXTURES: CiteFixture[] = [
  {
    id: 'openfda',
    href: 'https://open.fda.gov/',
    cite: {
      kind: 'web',
      title: 'openFDA',
      publisher: 'US Food and Drug Administration',
      place: 'Silver Spring (MD)',
      nlmPublisher: 'Food and Drug Administration (US)',
    },
  },
  {
    id: 'whoatcddd',
    href: 'https://atcddd.fhi.no/atc_ddd_index/',
    cite: {
      kind: 'web',
      title: 'ATC/DDD Index',
      editionYear: true,
      publisher: 'WHO Collaborating Centre for Drug Statistics Methodology',
      place: 'Oslo (Norway)',
      nlmPublisher: 'WHO Collaborating Centre for Drug Statistics Methodology',
    },
  },
  {
    id: 'classyfire',
    href: 'http://classyfire.wishartlab.com/',
    cite: {
      kind: 'article',
      authors: [
        'Djoumbou Feunang Y',
        'Eisner R',
        'Knox C',
        'Chepelev L',
        'Hastings J',
        'Owen G',
        'Fahy E',
        'Steinbeck C',
        'Subramanian S',
        'Bolton E',
        'Greiner R',
        'Wishart DS',
      ],
      title: 'ClassyFire: automated chemical classification with a comprehensive, computable taxonomy',
      journal: 'Journal of Cheminformatics',
      journalAbbr: 'J Cheminform',
      year: 2016,
      volume: '8',
      pages: '61',
      doi: '10.1186/s13321-016-0174-y',
      pmid: '27867422',
    },
  },
  {
    id: 'drugbank',
    href: 'https://go.drugbank.com/',
    cite: {
      kind: 'article',
      authors: [
        'Knox C',
        'Wilson M',
        'Klinger CM',
        'Franklin M',
        'Oler E',
        'Wilson A',
        'Pon A',
        'Cox J',
        'Chin NEL',
        'Strawbridge SA',
        'Garcia-Patino M',
        'Kruger R',
        'Sivakumaran A',
        'Sanford S',
        'Doshi R',
        'Khetarpal N',
        'Fatokun O',
        'Doucet D',
        'Zubkowski A',
        'Rayat DY',
        'Jackson H',
        'Harford K',
        'Anjum A',
        'Zakir M',
        'Wang F',
        'Tian S',
        'Lee B',
        'Liigand J',
        'Peters H',
        'Wang RQR',
        'Nguyen T',
        'So D',
        'Sharp M',
        'da Silva R',
        'Gabriel C',
        'Scantlebury J',
        'Jasinski M',
        'Ackerman D',
        'Jewison T',
        'Sajed T',
        'Gautam V',
        'Wishart DS',
      ],
      title: 'DrugBank 6.0: the DrugBank Knowledgebase for 2024',
      journal: 'Nucleic Acids Research',
      journalAbbr: 'Nucleic Acids Res',
      year: 2024,
      volume: '52',
      issue: 'D1',
      pages: 'D1265-D1275',
      doi: '10.1093/nar/gkad976',
      pmid: '37953279',
    },
  },
  {
    id: 'lactmed',
    href: 'https://www.ncbi.nlm.nih.gov/books/NBK501922/',
    cite: {
      kind: 'web',
      title: 'Drugs and Lactation Database (LactMed)',
      publisher: 'National Institute of Child Health and Human Development',
      place: 'Bethesda (MD)',
      nlmPublisher: 'National Institute of Child Health and Human Development',
      since: 2006,
    },
  },
  {
    id: 'ecotox',
    href: 'https://cfpub.epa.gov/ecotox/',
    cite: {
      kind: 'article',
      authors: [
        'Olker JH',
        'Elonen CM',
        'Pilli A',
        'Anderson A',
        'Kinziger B',
        'Erickson S',
        'Skopinski M',
        'Pomplun A',
        'LaLone CA',
        'Russom CL',
        'Hoff D',
      ],
      title: 'The ECOTOXicology Knowledgebase: a curated database of ecologically relevant toxicity tests to support environmental research and risk assessment',
      journal: 'Environmental Toxicology and Chemistry',
      journalAbbr: 'Environ Toxicol Chem',
      year: 2022,
      volume: '41',
      issue: '6',
      pages: '1520-1539',
      doi: '10.1002/etc.5324',
      pmid: '35262228',
    },
  },
  {
    id: 'pubchem',
    href: 'https://pubchem.ncbi.nlm.nih.gov/',
    cite: {
      kind: 'article',
      authors: [
        'Kim S',
        'Chen J',
        'Cheng T',
        'Gindulyte A',
        'He J',
        'He S',
        'Li Q',
        'Shoemaker BA',
        'Thiessen PA',
        'Yu B',
        'Zaslavsky L',
        'Zhang J',
        'Bolton EE',
      ],
      title: 'PubChem 2025 update',
      journal: 'Nucleic Acids Research',
      journalAbbr: 'Nucleic Acids Res',
      year: 2025,
      volume: '53',
      issue: 'D1',
      pages: 'D1516-D1525',
      doi: '10.1093/nar/gkae1059',
      pmid: '39558165',
    },
  },
]
